/*
 * Copyright 2026 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.claimvatenrolmentfrontend.assets

object MessageLookup {

  object Base {
    val continue = "Continue"
    val change = "Change"
    val yes = "Yes"
    val no = "No"
    val tryAgain = "Try Again"
    val signOut = "Sign out"

    object Error {
      val title = "There is a problem"
      val error = "Error: "
    }

  }

  object Header {
    val signOut = "Sign out"
  }

  object BetaBanner {
    val title = "This is a new service – your feedback will help us to improve it."
  }

  object CaptureBusinessPostcode {
    val title = "What is the UK postcode where your business is registered for VAT? - Claim VAT Enrolment - GOV.UK"
    val heading = "What is the UK postcode where your business is registered for VAT?"
    val hint = "For example, AB1 2YZ"
    val link_text = "The business does not have a UK postcode"

    object Error {
      val emptyPostcode = "This field is required"
      val invalidPostcode = "Enter the postcode where your business is registered for VAT"
    }

  }

  object CaptureVatRegistrationDate {
    val title = "When did you become VAT registered? - Claim VAT Enrolment - GOV.UK"
    val heading = "When did you become VAT registered?"
    val para = "You can find this date on your VAT registration certificate."
    val hint = "For example, 6 4 2017"

    object Error {
      val invalidDate = "Enter a real date"
      val noDate = "Enter your VAT registration date"
      val futureDate = "VAT registration date must be in the past"
    }

  }

  object CaptureBox5Figure {
    val title = "What is your latest VAT Return total? - Claim VAT Enrolment - GOV.UK"
    val heading = "What is your latest VAT Return total?"
    val line_1 = "You can find this amount in box number 5 on your latest VAT Return submitted to HMRC."
    val line_2 = "Enter an amount in pounds including two decimal places. For example, £123.45 or £312.00"

    object Error {
      val noFigure = "Enter your latest VAT Return total or Box 5 amount"
      val invalidLength = "The Box 5 amount must be less than 14 digits"
      val invalidFormat = "Enter an amount with two decimal places, for example £123.45 or £312.00"
    }

  }

  object CaptureVatApplicationNumber {
    val title = "What is your VAT application number? - Claim VAT Enrolment - GOV.UK"
    val heading = "What is your VAT application number?"
    val line_1 = "This is the unique reference generated by an application to register for VAT."
    val line_2 = "The VAT application number was displayed on the screen after an application for VAT registration was made. It was also emailed and will be on the VAT registration letter we sent in the post."
    val hint = "It is 12 numbers and begins with ‘099’, for example 099 123456789."

    object Error {
      val invalidLength = "The VAT application number must be 12 numbers"
      val nothing = "Enter the VAT application number"
      val invalidFormat = "The VAT registration number must only contain numbers"
    }

  }

  object CaptureSubmittedVATReturn {
    val title = "Have you, or someone else, submitted VAT Returns for this business? - Claim VAT Enrolment - GOV.UK"
    val heading = "Have you, or someone else, submitted VAT Returns for this business?"
    val hint = "If a VAT Return has not yet been submitted for this business, select no."

    object Error {
      val errorMessage = "Select yes if you are submitting VAT returns"
    }

    val titleOld = "Are you currently submitting VAT Returns? - Claim VAT Enrolment - GOV.UK"
    val headingOld = "Are you currently submitting VAT Returns?"
  }

  object CaptureLastMonthSubmitted {
    val title = "Select the last month of your latest VAT accounting period - Claim VAT Enrolment - GOV.UK"
    val heading = "Select the last month of your latest VAT accounting period"
    val firstLine = "You can find this in your latest VAT Return submitted to HMRC."
    val panelFirstHeading = "Latest VAT accounting period, example 1"
    val panelFirstText = "You submit your VAT Return quarterly (every three months). In the ‘accounting period’ January to March, the last month in that ‘accounting period’ is March. You must therefore select March."
    val panelSecondHeading = "Latest VAT accounting period, example 2"
    val panelSecondText = "If you submit your VAT Return monthly, the last accounting period you ‘submitted for’ was January. You must select January."
    val hint = "Select the last month of your latest VAT accounting period."
    val januaryLabel = "January"
    val februaryLabel = "February"
    val marchLabel = "March"
    val aprilLabel = "April"
    val mayLabel = "May"
    val juneLabel = "June"
    val julyLabel = "July"
    val augustLabel = "August"
    val septemberLabel = "September"
    val octoberLabel = "October"
    val novemberLabel = "November"
    val decemberLabel = "December"

    object Error {
      val noMonthSelected = "Select a month"
    }

  }

  object CheckYourAnswers {
    val title = "Check Your Answers - Claim VAT Enrolment - GOV.UK"
    val heading = "Check Your Answers"
    val vatNumberRow = "VAT Number"
    val vatRegDateRow = "VAT Registration Date"
    val businessPostcodeRow = "Where your business is registered for VAT"
    val vatReturnsRow = "You are currently submitting VAT returns"
    val boxFiveRow = "Your VAT return total or Box 5 amount"
    val lastReturnMonthRow = "The last month in your latest accounting period"

  }

  object KnownFactsMismatch {
    val title = "We could not confirm your business - Claim VAT Enrolment - GOV.UK"
    val heading = "We could not confirm your business"
    val line_1 = "The information you provided does not match the details we have about your business."

    val ver2TitleHeading = "We could not confirm your business"
    val ver2Line_1 = "The details you provided are not the same as those that we have on record. They must match exactly the details on the VAT registration confirmation letter that we sent by post."
    val ver2Line_2 = "Check your details and try again."
  }

  object DifferentVatNumbersError {
    val title = "You have entered different VAT registration numbers - Claim VAT Enrolment - GOV.UK"
    val heading = "You have entered different VAT registration numbers"
    val line_1 = "The VAT registration number you have provided does not match exactly the number previously used. For security, this session must be restarted."
    val line_2 = "To make another attempt, sign out and sign in."
  }

  object KnownFactsMismatchWithin24hrs {
    val title = "Access to your VAT online account is still locked - Claim VAT Enrolment - GOV.UK"
    val heading = "Access to your VAT online account is still locked"
    val line_1 = "In the last 24 hours, business details were provided that did not match exactly those that we have on record. For security, we have locked access for 24 hours from the last failed attempt."
    val line_2 = "Before your next attempt, check you have the correct information. This can be found on your latest VAT Return or the VAT registration confirmation letter we sent by post."
    val line_3 = "The HMRC helpline will not be able to give access within 24 hours of the last failed attempt."
    val link = "Go back to your Business Tax Account"
    val link_url = "/business-account/add-tax/vat/interstitial"
  }

  object ThirdAttemptLockout {
    val title = "We could not confirm your business so we have locked access for 24 hours - Claim VAT Enrolment - GOV.UK"
    val heading = "We could not confirm your business so we have locked access for 24 hours"
    val line_1 = "The details you provided must match exactly those that we have on record. Before your next attempt, check you have the correct information. This can be found on your latest VAT Return or the VAT registration confirmation letter we sent by post."
    val line_2 = "For security, access has been locked for 24 hours from the last failed attempt."
    val line_3 = "The HMRC helpline will not be able to give you access within this time period."
    val button_text = "Go back to your Business Tax Account"
    val link = "/business-account/add-tax/vat/interstitial"

  }

  object InvalidAccountType {
    val title = "You are not authorised to use this service - Claim VAT Enrolment - GOV.UK"
    val heading = "You are not authorised to use this service"
    val line_1 = "Contact the person who set up the account. You need authority to enrol the business for VAT."

  }

  object UnmatchedUserError {
    val title = "You cannot use this service - Claim VAT Enrolment - GOV.UK"
    val heading = "You cannot use this service"
    val link = "manage who can access your taxes, duties and schemes"
    val line_1 = s"Go to your business tax account to $link."

  }

  object ServiceTimeoutError {
    val title = "There has been a problem - Claim VAT Enrolment - GOV.UK"
    val heading = "There has been a problem"
    val line_1 = "This is because you started this claim more than 60 minutes ago."
    val line_2 = "We have not saved your details."
    val line_3 = "You must complete your VAT enrolment claim within 60 minutes of starting your claim or we delete the details you provided."
    val link = "start your VAT enrolment claim"
    val line_4 = s"You’ll need to $link again."

  }
  object EnrolmentAlreadyAllocatedError {
    val title = "This business’s VAT has already been added to another business tax account - Claim VAT Enrolment - GOV.UK"
    val heading = "This business’s VAT has already been added to another business tax account"
    val line_1 = "This business’s VAT has been added to a different business tax account."
    val line_2 = "It was added using different HMRC sign in details than the ones you signed in with."
    val line_3 = "To view and manage this business’s VAT, try signing in again with other HMRC sign in details."
    val link = "find or recover your HMRC sign in details here"
    val button_text = "Go back to your business tax account"
    val link_url = "https://www.access.service.gov.uk/account-recovery/forgot-userid-password/check-your-emails"
  }

  object SignUpCompleteClient {
    val title = "You have added VAT to your business tax account - Claim VAT Enrolment - GOV.UK"
    val heading = "You have added VAT to your business tax account"
    val line_1 = "You can now use your business tax account to:"
    val bullet1 = "see what you owe"
    val bullet2 = "check your deadlines"
    val bullet3 = "pay your VAT"
    val bullet4 = "tell us about any changes to your business"
    val link_url = "https://www.tax.service.gov.uk/business-account"
  }

}
